// <auto-generated />
using System;
using DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311054436_AddMaterialFileSizeBytes")]
    partial class AddMaterialFileSizeBytes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusinessObject.Models.Assignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("due_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("DRAFT")
                        .HasColumnName("status");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint")
                        .HasColumnName("teacher_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assignments");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_assignments_class_id");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_assignments_teacher_id");

                    b.ToTable("assignments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ClassId = 2L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Xây dựng ứng dụng MAUI có ít nhất 3 màn hình với Shell Navigation và truyền dữ liệu giữa các trang.",
                            DueDate = new DateTime(2026, 3, 16, 16, 59, 0, 0, DateTimeKind.Utc),
                            Status = "PUBLISHED",
                            TeacherId = 2L,
                            Title = "Lab 1: MAUI Navigation",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2L,
                            ClassId = 3L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tạo một scene Unity có ánh sáng directional, mặt phẳng (Plane), và ít nhất 1 GameObject có Rigidbody và Collider.",
                            DueDate = new DateTime(2026, 3, 15, 16, 59, 0, 0, DateTimeKind.Utc),
                            Status = "PUBLISHED",
                            TeacherId = 2L,
                            Title = "Lab 1: Unity Scene",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.AssignmentOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<bool>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_correct");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    b.HasKey("Id")
                        .HasName("pk_assignment_options");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_assignment_options_question_id");

                    b.ToTable("assignment_options", null, t =>
                        {
                            t.HasCheckConstraint("ck_assignment_options_order", "\"order\" > 0");
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.AssignmentQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("assignment_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<decimal>("Points")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("points");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assignment_questions");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_assignment_questions_assignment_id");

                    b.ToTable("assignment_questions", null, t =>
                        {
                            t.HasCheckConstraint("ck_assignment_questions_order", "\"order\" > 0");

                            t.HasCheckConstraint("ck_assignment_questions_points", "points > 0");
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.Class", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("MaxStudents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("max_students");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint")
                        .HasColumnName("teacher_id");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("thumbnail_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_classes");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_classes_teacher_id");

                    b.ToTable("classes", null, t =>
                        {
                            t.HasCheckConstraint("ck_classes_max_students", "max_students > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ôn luyện toàn bộ chương trình Toán lớp 12.",
                            MaxStudents = 20,
                            Name = "Toán 12 — Luyện thi THPT",
                            Status = "ACTIVE",
                            Subject = "Toán",
                            TeacherId = 2L,
                            ThumbnailUrl = "https://placehold.co/400?text=Course",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cross-Platform Mobile App Development With .NET MAUI",
                            MaxStudents = 30,
                            Name = "PRN222",
                            Status = "ACTIVE",
                            Subject = "PRN222",
                            TeacherId = 2L,
                            ThumbnailUrl = "https://placehold.co/400?text=Course",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Unity Game Development — Scripting & Physics",
                            MaxStudents = 30,
                            Name = "PRU213",
                            Status = "ACTIVE",
                            Subject = "PRU213",
                            TeacherId = 2L,
                            ThumbnailUrl = "https://placehold.co/400?text=Course",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.ClassMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_class_members");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_class_members_student_id");

                    b.HasIndex("ClassId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("ix_class_members_class_id_student_id");

                    b.ToTable("class_members", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ClassId = 1L,
                            JoinedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "ACTIVE",
                            StudentId = 3L
                        },
                        new
                        {
                            Id = 2L,
                            ClassId = 2L,
                            JoinedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "ACTIVE",
                            StudentId = 3L
                        },
                        new
                        {
                            Id = 3L,
                            ClassId = 3L,
                            JoinedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "ACTIVE",
                            StudentId = 3L
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.Feedback", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("score");

                    b.Property<long>("SubmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("submission_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_feedbacks");

                    b.HasIndex("SubmissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_feedbacks_submission_id");

                    b.ToTable("feedbacks", null, t =>
                        {
                            t.HasCheckConstraint("ck_feedbacks_score", "score >= 0");
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.Invoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("issued_at");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("paid_at");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint")
                        .HasColumnName("teacher_id");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_invoices_class_id");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_invoices_teacher_id");

                    b.ToTable("invoices", null, t =>
                        {
                            t.HasCheckConstraint("ck_invoices_period", "period_start < period_end");

                            t.HasCheckConstraint("ck_invoices_total_amount", "total_amount > 0");
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.Material", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UploadedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("pk_materials");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_materials_class_id");

                    b.HasIndex("UploadedBy")
                        .HasDatabaseName("ix_materials_uploaded_by");

                    b.ToTable("materials", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ClassId = 2L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tổng quan về .NET MAUI, XAML cơ bản và cấu trúc project.",
                            FileType = "PDF",
                            FileUrl = "https://storage.learnmate.vn/materials/prn222-slide-01.pdf",
                            Status = "ACTIVE",
                            Title = "Slide Buổi 1 — .NET MAUI Introduction",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UploadedBy = 2L
                        },
                        new
                        {
                            Id = 2L,
                            ClassId = 3L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hướng dẫn cài đặt Unity Hub, tạo project và làm quen với Editor.",
                            FileType = "PDF",
                            FileUrl = "https://storage.learnmate.vn/materials/pru213-slide-01.pdf",
                            Status = "ACTIVE",
                            Title = "Slide Buổi 1 — Unity Editor Overview",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UploadedBy = 2L
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("ix_notifications_user_id_is_read");

                    b.ToTable("notifications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Content = "Bạn đã tham gia lớp Cross-Platform Mobile App Development thành công!",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = true,
                            Title = "Chào mừng đến PRN222",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3L
                        },
                        new
                        {
                            Id = 2L,
                            Content = "Bạn đã tham gia lớp Unity Game Development thành công!",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = true,
                            Title = "Chào mừng đến PRU213",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3L
                        },
                        new
                        {
                            Id = 3L,
                            Content = "Lab 1: MAUI Navigation đã được đăng. Hạn nộp: 16/03/2026.",
                            CreatedAt = new DateTime(2026, 3, 7, 1, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Title = "Bài tập mới — PRN222",
                            UpdatedAt = new DateTime(2026, 3, 7, 1, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            Content = "Lab 1: Unity Scene đã được đăng. Hạn nộp: 15/03/2026.",
                            CreatedAt = new DateTime(2026, 3, 7, 2, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Title = "Bài tập mới — PRU213",
                            UpdatedAt = new DateTime(2026, 3, 7, 2, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3L
                        },
                        new
                        {
                            Id = 5L,
                            Content = "PRN222: Thứ 2 & Thứ 4 lúc 07:30. PRU213: Thứ 3 & Thứ 5 lúc 13:00.",
                            CreatedAt = new DateTime(2026, 3, 8, 3, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Title = "Lịch học tuần này",
                            UpdatedAt = new DateTime(2026, 3, 8, 3, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3L
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.OtpVerification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expired_at");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_otp_verifications");

                    b.HasIndex("UserId", "IsUsed")
                        .HasDatabaseName("ix_otp_verifications_user_id_is_used");

                    b.ToTable("otp_verifications", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Models.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_payments_class_id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_payments_invoice_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_payments_student_id");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_payments_amount", "amount > 0");
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.Schedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsTrial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_trial");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("SCHEDULED")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_schedules");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_schedules_class_id");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("ix_schedules_start_time");

                    b.ToTable("schedules", null, t =>
                        {
                            t.HasCheckConstraint("ck_schedules_time", "end_time > start_time");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ClassId = 2L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 3, 9, 2, 30, 0, 0, DateTimeKind.Utc),
                            IsTrial = false,
                            StartTime = new DateTime(2026, 3, 9, 0, 30, 0, 0, DateTimeKind.Utc),
                            Status = "SCHEDULED",
                            Title = "PRN222 — Buổi 1: Giới thiệu .NET MAUI & XAML",
                            Type = "REGULAR",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2L,
                            ClassId = 2L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 3, 11, 2, 30, 0, 0, DateTimeKind.Utc),
                            IsTrial = false,
                            StartTime = new DateTime(2026, 3, 11, 0, 30, 0, 0, DateTimeKind.Utc),
                            Status = "SCHEDULED",
                            Title = "PRN222 — Buổi 2: Data Binding & MVVM",
                            Type = "REGULAR",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3L,
                            ClassId = 3L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 3, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsTrial = false,
                            StartTime = new DateTime(2026, 3, 10, 6, 0, 0, 0, DateTimeKind.Utc),
                            Status = "SCHEDULED",
                            Title = "PRU213 — Buổi 1: Unity Editor & Scene Setup",
                            Type = "REGULAR",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4L,
                            ClassId = 3L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 3, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsTrial = false,
                            StartTime = new DateTime(2026, 3, 12, 6, 0, 0, 0, DateTimeKind.Utc),
                            Status = "SCHEDULED",
                            Title = "PRU213 — Buổi 2: Rigidbody Physics & Colliders",
                            Type = "REGULAR",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.StudentProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("GradeLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("grade_level");

                    b.Property<string>("ParentContact")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("parent_contact");

                    b.Property<int>("StudyStreakDays")
                        .HasColumnType("integer")
                        .HasColumnName("study_streak_days");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_student_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_profiles_user_id");

                    b.ToTable("student_profiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Nguyen Minh Tuan",
                            GradeLevel = "12",
                            StudyStreakDays = 8,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3L
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.Submission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("assignment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_url");

                    b.Property<decimal?>("Score")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("DRAFT")
                        .HasColumnName("status");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_submissions");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_submissions_assignment_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_submissions_student_id");

                    b.HasIndex("AssignmentId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("ix_submissions_assignment_id_student_id");

                    b.ToTable("submissions", null, t =>
                        {
                            t.HasCheckConstraint("ck_submissions_score", "score IS NULL OR score >= 0");
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.SubmissionAnswer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("text")
                        .HasColumnName("answer_text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    b.Property<long>("SubmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("submission_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_submission_answers");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_submission_answers_question_id");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("ix_submission_answers_submission_id");

                    b.ToTable("submission_answers", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Models.SubmissionAnswerOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("OptionId")
                        .HasColumnType("bigint")
                        .HasColumnName("option_id");

                    b.Property<long>("SubmissionAnswerId")
                        .HasColumnType("bigint")
                        .HasColumnName("submission_answer_id");

                    b.HasKey("Id")
                        .HasName("pk_submission_answer_options");

                    b.HasIndex("OptionId")
                        .HasDatabaseName("ix_submission_answer_options_option_id");

                    b.HasIndex("SubmissionAnswerId", "OptionId")
                        .IsUnique()
                        .HasDatabaseName("ix_submission_answer_options_submission_answer_id_option_id");

                    b.ToTable("submission_answer_options", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Models.TeacherProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("BankAccount")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bank_account");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("hourly_rate");

                    b.Property<decimal>("RatingAvg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("rating_avg");

                    b.Property<string>("Subjects")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subjects");

                    b.Property<int>("TotalRatingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_rating_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_teacher_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_teacher_profiles_user_id");

                    b.ToTable("teacher_profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_teacher_profiles_hourly_rate", "hourly_rate > 0");

                            t.HasCheckConstraint("ck_teacher_profiles_rating_avg", "rating_avg BETWEEN 0 AND 5");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Bio = "Giáo viên Toán với 5 năm kinh nghiệm.",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Nguyen Van A",
                            HourlyRate = 200000m,
                            RatingAvg = 0m,
                            Subjects = "Toán, Vật Lý",
                            TotalRatingCount = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2L
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.TeacherRating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("rating");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint")
                        .HasColumnName("teacher_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_teacher_ratings");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_teacher_ratings_class_id");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_teacher_ratings_teacher_id");

                    b.HasIndex("StudentId", "TeacherId", "ClassId")
                        .IsUnique()
                        .HasDatabaseName("ix_teacher_ratings_student_id_teacher_id_class_id");

                    b.ToTable("teacher_ratings", null, t =>
                        {
                            t.HasCheckConstraint("ck_teacher_ratings_rating", "rating BETWEEN 1.0 AND 5.0");
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AvatarUrl = "https://placehold.co/400?text=Admin",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@learnmate.vn",
                            IsActive = true,
                            PasswordHash = "$2a$12$BgRmemonnrWXu0O0hABfSuRgIBIjUevBcIGTk53b.y0oPqW45tCka",
                            Role = "ADMIN",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2L,
                            AvatarUrl = "https://placehold.co/400?text=Teacher",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "teacher@learnmate.vn",
                            IsActive = true,
                            PasswordHash = "$2a$12$BgRmemonnrWXu0O0hABfSuRgIBIjUevBcIGTk53b.y0oPqW45tCka",
                            Role = "TEACHER",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3L,
                            AvatarUrl = "https://placehold.co/400?text=Student",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student@learnmate.vn",
                            IsActive = true,
                            PasswordHash = "$2a$12$BgRmemonnrWXu0O0hABfSuRgIBIjUevBcIGTk53b.y0oPqW45tCka",
                            Role = "STUDENT",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.VideoSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("MeetingId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("meeting_id");

                    b.Property<string>("MeetingUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("meeting_url");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<long>("ScheduleId")
                        .HasColumnType("bigint")
                        .HasColumnName("schedule_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("WAITING")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_video_sessions");

                    b.HasIndex("ScheduleId")
                        .IsUnique()
                        .HasDatabaseName("ix_video_sessions_schedule_id");

                    b.ToTable("video_sessions", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Models.Assignment", b =>
                {
                    b.HasOne("BusinessObject.Models.Class", "Class")
                        .WithMany("Assignments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_classes_class_id");

                    b.HasOne("BusinessObject.Models.User", "Teacher")
                        .WithMany("Assignments")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_users_teacher_id");

                    b.Navigation("Class");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BusinessObject.Models.AssignmentOption", b =>
                {
                    b.HasOne("BusinessObject.Models.AssignmentQuestion", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_options_assignment_questions_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("BusinessObject.Models.AssignmentQuestion", b =>
                {
                    b.HasOne("BusinessObject.Models.Assignment", "Assignment")
                        .WithMany("Questions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_questions_assignments_assignment_id");

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("BusinessObject.Models.Class", b =>
                {
                    b.HasOne("BusinessObject.Models.User", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_classes_users_teacher_id");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BusinessObject.Models.ClassMember", b =>
                {
                    b.HasOne("BusinessObject.Models.Class", "Class")
                        .WithMany("ClassMembers")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_class_members_classes_class_id");

                    b.HasOne("BusinessObject.Models.User", "Student")
                        .WithMany("ClassMembers")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_class_members_users_student_id");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BusinessObject.Models.Feedback", b =>
                {
                    b.HasOne("BusinessObject.Models.Submission", "Submission")
                        .WithOne("Feedback")
                        .HasForeignKey("BusinessObject.Models.Feedback", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_feedbacks_submissions_submission_id");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("BusinessObject.Models.Invoice", b =>
                {
                    b.HasOne("BusinessObject.Models.Class", "Class")
                        .WithMany("Invoices")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_classes_class_id");

                    b.HasOne("BusinessObject.Models.User", "Teacher")
                        .WithMany("Invoices")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_users_teacher_id");

                    b.Navigation("Class");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BusinessObject.Models.Material", b =>
                {
                    b.HasOne("BusinessObject.Models.Class", "Class")
                        .WithMany("Materials")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_materials_classes_class_id");

                    b.HasOne("BusinessObject.Models.User", "Uploader")
                        .WithMany("Materials")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_materials_users_uploaded_by");

                    b.Navigation("Class");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("BusinessObject.Models.Notification", b =>
                {
                    b.HasOne("BusinessObject.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.Models.OtpVerification", b =>
                {
                    b.HasOne("BusinessObject.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otp_verifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.Models.Payment", b =>
                {
                    b.HasOne("BusinessObject.Models.Class", "Class")
                        .WithMany("Payments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_classes_class_id");

                    b.HasOne("BusinessObject.Models.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_payments_invoices_invoice_id");

                    b.HasOne("BusinessObject.Models.User", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_users_student_id");

                    b.Navigation("Class");

                    b.Navigation("Invoice");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BusinessObject.Models.Schedule", b =>
                {
                    b.HasOne("BusinessObject.Models.Class", "Class")
                        .WithMany("Schedules")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedules_classes_class_id");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("BusinessObject.Models.StudentProfile", b =>
                {
                    b.HasOne("BusinessObject.Models.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("BusinessObject.Models.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.Models.Submission", b =>
                {
                    b.HasOne("BusinessObject.Models.Assignment", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submissions_assignments_assignment_id");

                    b.HasOne("BusinessObject.Models.User", "Student")
                        .WithMany("Submissions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_submissions_users_student_id");

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BusinessObject.Models.SubmissionAnswer", b =>
                {
                    b.HasOne("BusinessObject.Models.AssignmentQuestion", "Question")
                        .WithMany("SubmissionAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_submission_answers_assignment_questions_question_id");

                    b.HasOne("BusinessObject.Models.Submission", "Submission")
                        .WithMany("Answers")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submission_answers_submissions_submission_id");

                    b.Navigation("Question");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("BusinessObject.Models.SubmissionAnswerOption", b =>
                {
                    b.HasOne("BusinessObject.Models.AssignmentOption", "Option")
                        .WithMany("SubmissionAnswerOptions")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_submission_answer_options_assignment_options_option_id");

                    b.HasOne("BusinessObject.Models.SubmissionAnswer", "SubmissionAnswer")
                        .WithMany("SelectedOptions")
                        .HasForeignKey("SubmissionAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submission_answer_options_submission_answers_submission_ans");

                    b.Navigation("Option");

                    b.Navigation("SubmissionAnswer");
                });

            modelBuilder.Entity("BusinessObject.Models.TeacherProfile", b =>
                {
                    b.HasOne("BusinessObject.Models.User", "User")
                        .WithOne("TeacherProfile")
                        .HasForeignKey("BusinessObject.Models.TeacherProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.Models.TeacherRating", b =>
                {
                    b.HasOne("BusinessObject.Models.Class", "Class")
                        .WithMany("TeacherRatings")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_ratings_classes_class_id");

                    b.HasOne("BusinessObject.Models.User", "Student")
                        .WithMany("RatingsGiven")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_ratings_users_student_id");

                    b.HasOne("BusinessObject.Models.User", "Teacher")
                        .WithMany("RatingsReceived")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_ratings_users_teacher_id");

                    b.Navigation("Class");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BusinessObject.Models.VideoSession", b =>
                {
                    b.HasOne("BusinessObject.Models.Schedule", "Schedule")
                        .WithOne("VideoSession")
                        .HasForeignKey("BusinessObject.Models.VideoSession", "ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_video_sessions_schedules_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("BusinessObject.Models.Assignment", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("BusinessObject.Models.AssignmentOption", b =>
                {
                    b.Navigation("SubmissionAnswerOptions");
                });

            modelBuilder.Entity("BusinessObject.Models.AssignmentQuestion", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("SubmissionAnswers");
                });

            modelBuilder.Entity("BusinessObject.Models.Class", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("ClassMembers");

                    b.Navigation("Invoices");

                    b.Navigation("Materials");

                    b.Navigation("Payments");

                    b.Navigation("Schedules");

                    b.Navigation("TeacherRatings");
                });

            modelBuilder.Entity("BusinessObject.Models.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BusinessObject.Models.Schedule", b =>
                {
                    b.Navigation("VideoSession");
                });

            modelBuilder.Entity("BusinessObject.Models.Submission", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("BusinessObject.Models.SubmissionAnswer", b =>
                {
                    b.Navigation("SelectedOptions");
                });

            modelBuilder.Entity("BusinessObject.Models.User", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("ClassMembers");

                    b.Navigation("Classes");

                    b.Navigation("Invoices");

                    b.Navigation("Materials");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("RatingsGiven");

                    b.Navigation("RatingsReceived");

                    b.Navigation("StudentProfile");

                    b.Navigation("Submissions");

                    b.Navigation("TeacherProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
